# -*- coding: utf-8 -*-
"""text_list_manipulation_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E4il4HJMwvr8GjRfMREBPMPi7hvhPF8B
"""

import os

def get_filename_without_extension(filename):
    return '.'.join(filename.split('.')[:-1])

# método para remover os duplicados de uma lista
def remover_duplicados(lista):
    return list(dict.fromkeys(lista))

# método para listar os nomes de ficheiros sem extensão
def listar_nomes_ficheiros_sem_extensao(pasta):
    lista_ficheiros = os.listdir(pasta)
    lista_ficheiros = [f for f in lista_ficheiros if os.path.isfile(os.path.join(pasta, f))]
    lista_ficheiros_sem_extensao = [os.path.splitext(f)[0] for f in lista_ficheiros]
    return lista_ficheiros_sem_extensao